let strip = neopixel.create(DigitalPin.P2, 16, NeoPixelMode.RGB)
basic.forever(function () {
    strip.showColor(neopixel.colors(NeoPixelColors.Violet))
    basic.pause(500)
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(500)
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    basic.pause(500)
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    basic.pause(500)
    strip.showColor(neopixel.colors(NeoPixelColors.Orange))
    basic.pause(500)
})
basic.forever(function () {
    pins.servoWritePin(AnalogPin.P0, 80)
    pins.servoWritePin(AnalogPin.P1, 140)
    basic.pause(1000)
    pins.servoWritePin(AnalogPin.P0, 140)
    pins.servoWritePin(AnalogPin.P1, 80)
    basic.pause(1000)
})
